version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'my-mongo-container'
    environment:
      - MONGO_INITDB_DATABASE=your-database-name
    ports:
      - '27017-27019:27017-27019'

